
[target.x86_64-pc-windows-msvc]
rustflags = [
    "-C", "link-arg=Mfplat.lib",
    "-C", "link-arg=Strmiids.lib",
    "-C", "link-arg=Mfuuid.lib",
    "-C", "link-arg=Bcrypt.lib",
    "-C", "link-arg=Secur32.lib",
    "-C", "link-arg=Ole32.lib",
    "-C", "link-arg=User32.lib"
]
